port: 7890                 #本地http代理端口
socks-port: 7891           #本地socks5代理端口
mixed-port: 7890             #本地混合代理(http和socks5合并）端口
redir-port: 7892           #本地Linux/macOS Redir代理端口
tproxy-port: 7893          #本地Linux Tproxy代理端口

geodata-mode: true         #【Meta专属】使用geoip.dat数据库(默认：false使用mmdb数据库)
tcp-concurrent: false         #【Meta专属】TCP连接并发，如果域名解析结果对应多个IP，
                             # 并发所有IP，选择握手最快的IP进行连接

allow-lan: false                  #允许局域网连接(false/true)
bind-address:                     #监听IP白名单（当allow-lan：true），只允许列表设备
  '*'                             #全部设备
  # 192.168.122.11                #单个ip4地址
  # "[aaaa::a8aa:ff:fe09:57d8]"   #单个ip6地址

unified-delay: true #在原版配置文件中没找到

mode: rule                 #clash工作模式（rule/global/direct,meta暂不支持script）
log-level: info            #日志等级（info/warning/error/debug/silent）
ipv6: true                #ip6开关，当为false时，停止解析hostanmes为ip6地址
udp: true #在原版配置文件中没找到
enable-process: false
sniffer:                         #【Meta专属】sniffer域名嗅探器
  enable: true                   #嗅探开关
  sniffing:                      #嗅探协议对象：目前支持tls/http
    - tls
    - http
  skip-domain:                   #列表中的sni字段，保留mapping结果，不通过嗅探还原域名
                                 #优先级比force-domain高
    - 'Mijia Cloud'              #米家设备，建议加
    - 'dlg.io.mi.com'
    - '+.apple.com'              #苹果域名，建议加
  # - '*.baidu.com'              #支持通配符

  force-domain:                  #需要强制嗅探的域名，默认只对IP嗅探
  # - '+'                        #去掉注释后等于全局嗅探
    - 'google.com'

  #port-whitelist:               #端口白名单，只对名单内的端口进行还原域名
  # - 80
  # - 443
  # - 8000-9000
profile:
  store-selected: true
  store-fake-ip: true
external-controller: 127.0.0.1:9090
geox-url:
  geoip: 'https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip-only-cn-private.dat'
  geosite: 'https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geosite.dat'
  mmdb: 'https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb'
tun:
  enable: true
  device: Meta
  stack: gvisor
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true
  strict-route: false
#ebpf配置
ebpf:
  redirect-to-tun: # UDP+TCP 使用该功能请勿启用 auto-route
    - wlo1

dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:1053
  use-hosts: true
  enhanced-mode: redir-host
  # enhanced-mode: fake-ip
  # fake-ip-range: 28.0.0.1/8
  # fake-ip-filter:
  #   - "*"
  #   - "+.lan"
  #   - "+.stun.*.*"
  #   - "+.stun.*.*.*"
  #   - "+.stun.*.*.*.*"
  #   - "+.stun.*.*.*.*.*"
  #   - lens.l.google.com
  #   - '*.mcdn.bilivideo.cn'
  #   - 'connect.rom.miui.com'
  #   - 'localhost.ptlogin2.qq.com'
  #   - '+.msftnsci.com'
  #   - '+.msftconnecttest.com'
  default-nameserver:
    - '114.114.114.114#REJECT'
  proxy-server-nameserver:
    - 'https://1.12.12.12/dns-query#DNS'        # dnspod
    - 'https://223.5.5.5/dns-query#DNS'         # alidns'
  nameserver:
    - 'https://1.1.1.1/dns-query#Proxy'           # CF
    - 'tcp://8.8.4.4#Proxy'           # google
  fallback:
    - '119.29.29.29#Domestic'   # dnspod
    - '223.5.5.5#Domestic'      # alidns
  fallback-filter:
    geoip: true
    geoip-code: '!CN'
    geosite: 
      - 'CN'
      - 'bilibili'
      - 'tiktok'
      - 'douyu'
      - 'huya'
      - 'category-games@cn'
      - 'tencent'
      - 'apple-cn'
    domain:
      - '+.bidiys.cc'
      - '+.xinhuanet.com'
      - '+.81.cn'
      - '+.news.cn'

proxies:

#此处用来放本地免流配置，本地免流只能免80/443端口的TCP，其他连接（包括所有udp）不行

proxy-providers:
  
  ikuuu:
    type: http
    url: "https://example.com"
    path: ./ProxyProviders/ikuuu.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Local:
    type: file
    path: ./ProxyProviders/Local.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  
proxy-groups:
  - name: DNS
    type: select
    proxies:
      - DIRECT

  - name: Proxy
    type: select
    proxies:
      - ikuuu
      - DIRECT

  - name: ikuuu
    type: select
    use:
      - ikuuu

  - name: Local
    type: select
    use:
      - Local

  - name: Domestic
    type: select
    proxies:
      - DIRECT
      - Proxy

rule-providers:
    
rules:
  # 域名规则
  # 阻止
  - GEOSITE,category-ads-all,REJECT

  # 特殊域名放行
  - DOMAIN-KEYWORD,announce,DIRECT
  - DOMAIN-KEYWORD,torrent,DIRECT
  - DOMAIN-KEYWORD,tracker,DIRECT
  - DOMAIN-SUFFIX,smtp,DIRECT
  - DOMAIN-SUFFIX,local,DIRECT
  # 抢跑规则
  - GEOSITE,bytedance@!cn,Proxy
  # GEOSITE 直连放行
  - GEOSITE,category-games@cn,Domestic
  - GEOSITE,bytedance,Domestic
  - GEOSITE,bilibili,Domestic
  - GEOSITE,douyu,Domestic
  - GEOSITE,huya,Domestic
  - GEOSITE,tencent,Domestic
  - GEOSITE,apple-cn,Domestic
  - GEOSITE,ehentai,Domestic
  # 强制直连域名
  - DOMAIN-SUFFIX,'bidiys.cc',Domestic
  - DOMAIN-SUFFIX,'81.cn',Domestic
  - DOMAIN-SUFFIX,'xinhuanet.com',Domestic
  - DOMAIN-SUFFIX,'news.cn',Domestic
  - DOMAIN-SUFFIX,'ypojie.com',Domestic

  # GEOSITE 代理
  - GEOSITE,firefox,DIRECT
  - GEOSITE,mozilla,DIRECT

  - GEOSITE,hoyoverse,Proxy
  - GEOSITE,mihoyo-cn,DIRECT

  - GEOSITE,github,Proxy
  - GEOSITE,gitlab,Proxy
  - GEOSITE,google,Proxy
  - GEOSITE,microsoft,DIRECT
  # 兜底规则
  - GEOSITE,CN,Domestic
  # IP 规则
  - GEOIP,PRIVATE,DIRECT,no-resolve
  # mosdns 规则
  - IP-CIDR,120.53.53.53/32,DIRECT,no-resolve
  - IP-CIDR,223.5.5.5/32,DIRECT,no-resolve
  - IP-CIDR,8.8.8.8/32,Proxy,no-resolve
  - IP-CIDR,1.1.1.1/32,Proxy,no-resolve
  # 兜底规则
  - GEOIP,CN,Domestic
  - MATCH,Proxy
